### ISSUE TITLE
Extension not getting activated after installation

### ISSUE THREAD

**Issue by divyajyoti09** [Elinvention/gnome-shell-extension-nasa-apod#46]
**Describe the bug**

I installed the extension in Ubuntu 18.04 but the extension is showing the following error in the tweaks and is not getting enabled:
```
TypeError: ExtensionUtils.initTranslations is not a function

Stack trace:
  init@/home/divyajyoti/.local/share/gnome-shell/extensions/nasa_apod@elinvention.ovh/prefs.js:24:5
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
```

**Operating system with version**
- Ubuntu 18.04 LTS

**GNOME Shell version**

- 3.38.4

**Installation method**
```
git clone https://github.com/Elinvention/gnome-shell-extension-nasa-apod.git $HOME/.local/share/gnome-shell/extensions/nasa_apod@elinvention.ovh
gnome-shell-extension-tool -e nasa_apod@elinvention.ovh
```

**Comment by Elinvention** [comment]
That's because the main branch supports only GNOME 40+ as you can see in `metadata.json`. You could checkout older commits that worked on gnome 3.38.
